protected/models/Config.php
<?php

/**
 * This is the model class for table "config".
 *
 * The followings are the available columns in table 'config':
 * @property integer $id
 * @property string $type
 * @property string $name
 * @property string $data1
 * @property string $data2
 */
class Config extends CActiveRecord
{
	public static $types = array('class' => 'Class', 'subject' => 'Subject', 'teacher' => 'Teacher', 'timetable' => 'Time Table', 'classtimetable' => 'Class Time Table');

	public static function byType($type)
	{
		$criteria=new CDbCriteria;
		$criteria->compare('type',$type,true);
		$dp = new CActiveDataProvider('Config', array(
			'criteria'=>$criteria,
		));
		return $dp->getData();
	}

	public static function bulkCreate($type, $data = false)
	{
		//$type = '7ATimeTable';
		$existing = self::byType($type);
		$rows = array();
		foreach ($existing as $cfg) $rows[$cfg->name] = $cfg;
		$existing = $rows;
		if (!$data)
		{
			$headers = array(
				'teacher' => 'Subjects	Classes',
				'subject' => 'Class	Empty',
				'timetable' => 'Timing	Config'
			);
			$rows = array('#Name	' . (isset($headers[$type]) ? $headers[$type] : 'Data1	Data2'));
			foreach ($existing as $cfg)
				$rows[] = $cfg->name . '	' . $cfg->data1 . '	' . $cfg->data2;
			return implode(PHP_EOL, $rows);
		}

		$msg = array();
		$rows = explode(PHP_EOL, $data);
		$line = 1;
		foreach ($rows as $row)
		{
			if ($row == '' || $row[0] ==  '#') continue;
			$bits = explode('	', $row);
			if (count($bits) < 3)
			{
				$msg[] = '#' . $line . ' - ' . $bits[0] . ' needs 3 fields';
			}
			else
			{
				$name = $bits[0];
				$new = !isset($existing[$name]);
				$model = $new ? new Config : $existing[$name];
				$model->name = $name;
				$model->type = $type;
				$model->data1 = $bits[1];
				$model->data2 = $bits[2];
				if ($model->save())
				{
					$msg[] = '#' . $line . ' - ' . $name . ($new ? ' (new)' : '') . ' saved ok';
				}
				else
				{
					$msg[] = '#' . $line . ' - ' . $name . ' error - ' . Formatter::errors($model);
				}
			}
			$line++;
		}
		return implode('<br />' . PHP_EOL, $msg);
	}

	private $classVal;

	public function getClass()
	{
		if ($this->classVal != null) return $this->classVal;
		if (substr($this->type, -9) == 'TimeTable');
			return substr($this->type, 0, strlen($this->type) - 9);
		return null;
	}

	public function setClass($value)
	{
		$this->classVal = $value;
	}

	public function getTypeEx()
	{
		return substr($this->type, -9) == 'TimeTable' ? 'classtimetable' : $this->type;
	}

	public function setTypeEx($value)
	{
		$this->type = $value;
	}

	protected function beforeSave()
	{
		if ($this->type == 'classtimetable')
			$this->type = $this->classVal . 'TimeTable';
		return parent::beforeSave();
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'config';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('type, name, data1', 'required'),
			array('type', 'length', 'max'=>32),
			array('name', 'length', 'max'=>128),
			array('data1, data2', 'length', 'max'=>2048),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, type, name, data1, data2', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'type' => 'Type',
			'name' => 'Name',
			'data1' => 'Data1',
			'data2' => 'Data2',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('type',$this->type,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('data1',$this->data1,true);
		$criteria->compare('data2',$this->data2,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Config the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ConfigController.php
<?php

class ConfigController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return $this->getAccessRules();
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Config;
		$bulkMessage = false;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_GET['bulk']) && isset($_GET['type']))
		{
			$model->data1 = Config::bulkCreate($model->type = $_GET['type']);
		}
		else if(isset($_POST['chkBulk']))
		{
			$type = $_POST['Config']['typeEx'];
			$model->type = $type;
			if ($type == '')
				$model->addError('type', 'Type cannot be blank');
			else if (isset($_POST['yt0']))
				$model->data1 = Config::bulkCreate($type);
			else
				$bulkMessage = Config::bulkCreate($type, $_POST['bulkData']);
		}
		else if(isset($_POST['Config']))
		{
			$model->attributes=$_POST['Config'];
			$model->typeEx = $_POST['Config']['typeEx'];
			$model->class = $_POST['Config']['class'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
			'bulkMessage'=>$bulkMessage,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		if(isset($_POST['Config']))
		{
			$model->attributes=$_POST['Config'];
			$model->typeEx = $_POST['Config']['typeEx'];
			$model->class = $_POST['Config']['class'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$type = isset($_GET['type']) ? $_GET['type'] : '';
		$config = array();
		if ($type == 'classtimetable') $config['criteria'] = array('condition'=>"type like '%TimeTable' and type != 'timetable'");
		else if ($type != '') $config['criteria'] = array('condition'=>"type='" . $type . "'");
		$dataProvider=new CActiveDataProvider('Config', $config);
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			'type'=>$type,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Config('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Config']))
			$model->attributes=$_GET['Config'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Config the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Config::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Config $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='config-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/config/_form.php
<?php
/* @var $this ConfigController */
/* @var $model Config */
/* @var $form CActiveForm */
Yii::app()->getClientScript()->registerScriptFile(Yii::app()->baseUrl . '/js/config-edit.js')
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'config-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'action' => isset($_GET['bulk']) ? Yii::app()->createUrl('/config/create') : '', //if create bulk called, it should allow to change the type
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'type'); ?>
		<?php echo $form->dropDownList($model,'typeEx',Formatter::includeBlank(Config::$types)); ?>
		<?php echo $form->error($model,'type'); ?>
	</div>

	<div class="row" id="classdiv">
		<?php echo $form->labelEx($model,'class'); ?>
		<?php echo $form->dropDownList($model,'class',AppHelper::classes()); ?>
		<?php echo $form->error($model,'class'); ?>
	</div>

<?php
if ($model->isNewRecord)
{
if (isset($_GET['bulk']) || isset($_POST['chkBulk']))
	Yii::app()->getClientScript()->registerScript('show-bulk',
		'$("#chkBulk")[0].checked = true; updateBulk();');
?>
<input id="chkBulk" name="chkBulk" type="checkbox" onchange="javascript:updateBulk();" />
<label for="chkBulk" style="display: inline;">Bulk Insert</label>
<?php echo CHtml::submitButton('Get Data'); ?>
<div id="bulk-div" style="display: none;">
	<div class="row">
		<?php echo $form->labelEx($model,'bulkData'); ?>
		<?php echo CHtml::textArea('bulkData', $model->data1, array('rows'=>10, 'cols'=>62)); ?>
	</div>
</div>
<?php }
if (!isset($_POST['bulkData'])) {
?>

 <div id="non-bulk-div">
	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'data1'); ?>
		<?php echo $form->textField($model,'data1',array('size'=>60,'maxlength'=>2048)); ?>
		<?php echo $form->error($model,'data1'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'data2'); ?>
		<?php echo $form->textField($model,'data2',array('size'=>60,'maxlength'=>2048)); ?>
		<?php echo $form->error($model,'data2'); ?>
	</div>
 </div>
<?php } ?>
	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/config/_search.php
<?php
/* @var $this ConfigController */
/* @var $model Config */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'type'); ?>
		<?php echo $form->dropDownList($model,'type',Formatter::includeBlank(Config::$types)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'data1'); ?>
		<?php echo $form->textField($model,'data1',array('size'=>60,'maxlength'=>2048)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'data2'); ?>
		<?php echo $form->textField($model,'data2',array('size'=>60,'maxlength'=>2048)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/config/_view.php
<?php
/* @var $this ConfigController */
/* @var $data Config */
if (!isset($data)) {
	echo '<tr><th>Name</th><th>Type</th><th>Data1</th><th>Data2</th></tr>';
	return;
}
?>
<tr>
	<td><?php echo CHtml::link($data->name, array('view', 'id'=>$data->id)); ?></td>
	<td><?php echo isset(Config::$types[$data->type]) ? Config::$types[$data->type] : $data->type; ?></td>
	<td><?php echo CHtml::encode($data->data1); ?></td>
	<td><?php echo CHtml::encode($data->data2); ?></td>
</tr>

protected/views/config/admin.php
<?php
/* @var $this ConfigController */
/* @var $model Config */

$this->breadcrumbs=array(
	'Configs'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Config', 'url'=>array('index')),
	array('label'=>'Create Config', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#config-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Configs</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'config-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'type',
		'name',
		'data1',
		'data2',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/config/create.php
<?php
/* @var $this ConfigController */
/* @var $model Config */

$this->breadcrumbs=array(
	'Configs'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Config', 'url'=>array('index')),
	array('label'=>'Manage Config', 'url'=>array('admin')),
);
?>

<h1>Create Config</h1>

<?php
if ($bulkMessage)
	echo $bulkMessage;
else
	$this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/config/index.php
<?php
/* @var $this ConfigController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Configs',
);

$this->menu=array(
	array('label'=>'Create Config', 'url'=>array('create')),
	array('label'=>'Manage Config', 'url'=>array('admin')),
);
?>
<script type="text/javascript">
function loadWithType()
{
	location = "./?type=" + $("#type").val();
}
</script>
<h1>Configs</h1>
<?php echo CHtml::dropDownList('type', $type, Formatter::includeBlank(Config::$types)); ?>
<?php echo ' ' . CHtml::button('GO', array('onclick'=>'js:loadWithType()' )); ?>
<br /><br />
<table>
<?php
$this->renderPartial('_view');
$this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>
</table>

protected/views/config/update.php
<?php
/* @var $this ConfigController */
/* @var $model Config */

$this->breadcrumbs=array(
	'Configs'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Config', 'url'=>array('index')),
	array('label'=>'Create Config', 'url'=>array('create')),
	array('label'=>'View Config', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Config', 'url'=>array('admin')),
);
?>

<h1>Update Config <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/config/view.php
<?php
/* @var $this ConfigController */
/* @var $model Config */

$this->breadcrumbs=array(
	'Configs'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List Config', 'url'=>array('index')),
	array('label'=>'Create Config', 'url'=>array('create')),
	array('label'=>'Update Config', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Config', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Config', 'url'=>array('admin')),
);
?>

<h1>View Config #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'type',
		'name',
		'data1',
		'data2',
	),
)); ?>